openapi: 3.0.0
info:
  title: common
  version: '1.0'
  contact:
    name: urykhy
    email: urykhy@gmail.com
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /enum:
    get:
      summary: Enumerate server methods
      tags:
        - Common
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      operationId: get-enum
  /status:
    get:
      summary: Get server status
      tags:
        - Common
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  load:
                    type: number
              examples:
                example-1:
                  value: {}
      operationId: get-status
  /profile:
    get:
      summary: Create flamegraph profile
      tags:
        - Common
      responses:
        '200':
          description: OK
          content:
            image/svg+xml:
              schema:
                type: string
      operationId: get-profile
      parameters:
        - schema:
            type: string
            default: cpu
            enum:
              - cpu
              - 'off'
          in: query
          name: type
        - schema:
            type: integer
            minimum: 1
            maximum: 20
            default: 5
          in: query
          name: duration
      description: ''
components:
  schemas: {}
tags:
  - name: Common
