openapi: 3.0.0
info:
  title: compress
  version: '1.0'
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /test1-octet:
    get:
      summary: Your GET endpoint
      operationId: get-test1-octet
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
      parameters:
        - schema:
            type: integer
            minimum: 1
          in: query
          name: size
          required: true
    parameters: []
