openapi: 3.0.0
info:
  title: discovery
  version: '1.0'
  contact:
    name: urykhy
    email: urykhy@gmail.com
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /discovery:
    get:
      summary: Dummy call
      tags:
        - Common
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
      operationId: get-discovery
components:
  schemas: {}
tags:
  - name: Test
