openapi: 3.0.0
info:
  title: tutorial
  version: '1.0'
  contact:
    name: urykhy
    email: urykhy@gmail.com
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /test:
    get:
      summary: Test method
      tags:
        - Tutorial
      operationId: get-test
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task_id:
                  type: string
                cookies:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: array
                        items:
                          type: string
                operation:
                  type: string
            examples: {}
      responses:
        '200':
          description: OK
    parameters: []
components:
  schemas: {}
tags:
  - name: Tutorial
