#!/bin/sh
# Begin /etc/init.d/

# Include the functions declared in the /etc/init.d/functions file
#
msg="firewall"
ipt="/sbin/iptables"
ip6="/sbin/ip6tables"

case "$1" in
        start)
            echo "Starting $msg"

            # create ipset rules for tor
            ipset create TOR hash:net
            ipset add TOR 195.82.146.0/23
            ipset add TOR 5.79.86.208    # coollib
            ipset add TOR 81.17.19.227   # flibusta
            ipset add TOR 104.24.106.53  # kinozal
            ipset add TOR 104.24.107.53
            ipset add TOR 193.189.117.92 # rutor
            ipset add TOR 185.61.149.0   # tfile
            ipset add TOR 62.133.161.112 # booktracker
            ipset add TOR 83.220.170.60  # booktracker
            ipset add TOR 188.42.196.32  # lurkmore.to
            ipset add TOR 81.17.30.22    # nnm-club.me

            NFLOG="NFLOG --nflog-group 1 --nflog-range=4096"

            # IPv6 really simple
            $ip6 -A INPUT -m conntrack --ctstate established,related -j ACCEPT
            $ip6 -A INPUT -i lo -j ACCEPT
            $ip6 -A INPUT -i tun* -m conntrack --ctstate new -j DROP
            $ip6 -A INPUT -p icmpv6 -j ACCEPT
            # syncthing
            $ip6 -A INPUT -p udp -m multiport --dports 21027 -j ACCEPT
            $ip6 -A INPUT -p tcp -m multiport --dports 22000 -j ACCEPT
            # torrents
            $ip6 -A INPUT -p udp -m multiport --dports 6771,6881:6889 -j ACCEPT
            $ip6 -A INPUT -p tcp -m multiport --dports 6771,6881:6889 -j ACCEPT
            $ip6 -A INPUT -j $NFLOG --nflog-prefix "ip6"
            $ip6 -P INPUT DROP
            $ip6 -P FORWARD DROP

            # IPv4
            # forward
            $ipt -A FORWARD -m conntrack --ctstate established,related -j ACCEPT
            $ipt -A FORWARD -i tun* -m conntrack --ctstate new -j DROP
            $ipt -A FORWARD -s 10.103.0.0/16 -j ACCEPT
            # docker networks
            $ipt -A FORWARD -s 172.16.0.0/12 -j ACCEPT
            #
            $ipt -A FORWARD -j $NFLOG --nflog-prefix "fwd"
            $ipt -P FORWARD DROP

            # setup conntrack helpers (or only wifi/eth0?)
            $ipt -A OUTPUT -t raw -p tcp --dport 21 -j CT --helper ftp
            $ipt -A PREROUTING -t raw -p tcp --dport 21 -j CT --helper ftp

            # lower prio for long-live http transfers
            $ipt -t mangle -A INPUT -i eth0 -p tcp -m multiport --sports 80,443 -m connmark --mark 0 -m connbytes --connbytes 1024000: --connbytes-dir both --connbytes-mode bytes -j CONNMARK --set-mark 0xa
            $ipt -t mangle -A FORWARD -i eth0 -p tcp -m multiport --sports 80,443 -m connmark --mark 0 -m connbytes --connbytes 1024000: --connbytes-dir both --connbytes-mode bytes -j CONNMARK --set-mark 0xa

            # skype
            $ipt -t mangle -A FORWARD -i wlan0 -o eth0 -p udp -m connmark --mark 0 -j CONNMARK --set-mark 0xb

            # dns proxy
            $ipt -t mangle -A OUTPUT -m owner --uid-owner _dnscrypt-proxy -m connmark --mark 0 -j CONNMARK --set-mark 0xc
            # tor
            $ipt -t mangle -A OUTPUT -m owner --uid-owner debian-tor -m connmark --mark 0 -j CONNMARK --set-mark 0xb

            # input
            $ipt -A INPUT -m conntrack --ctstate established,related -j ACCEPT
            # block traffic from open-vpn peers
            $ipt -A INPUT -i tun* -m conntrack --ctstate new -j REJECT
            # allow good local
            $ipt -A INPUT -i lo -j ACCEPT
            $ipt -A INPUT -i br0 -j ACCEPT
            $ipt -A INPUT -p icmp -j ACCEPT
            $ipt -A INPUT -s 10.103.0.0/16 -j ACCEPT

            # upnp from router
            $ipt -A INPUT -s 192.168.1.254 -p udp --dport 1900 -j ACCEPT
            $ipt -A INPUT -s 192.168.1.254 -p udp --sport 1900 -j ACCEPT

            # chain to log and drop (used in syn protection)
            $ipt -N LDROP
            $ipt -A LDROP -j $NFLOG --nflog-prefix "syn-in"
            $ipt -A LDROP -j DROP

            # tcp syn/connections limits
            $ipt -N TCPSYN
            $ipt -A TCPSYN -p tcp -m connlimit --connlimit-above 20 --connlimit-mask 32 -j REJECT --reject-with tcp-reset
            $ipt -A TCPSYN -m connlimit --connlimit-above 100 --connlimit-mask 24 -j LDROP
            $ipt -A TCPSYN -m hashlimit --hashlimit-above 50/second --hashlimit-mode srcip --hashlimit-srcmask 24 --hashlimit-name ddos -j LDROP
            $ipt -A TCPSYN -j RETURN
            $ipt -A INPUT -p tcp --syn -j TCPSYN

            # syncthing, open for all
            $ipt -A INPUT -p udp -m multiport --dports 21027 -j ACCEPT
            $ipt -A INPUT -p tcp -m multiport --dports 22000 -j ACCEPT

            # torrents
            $ipt -A INPUT -p udp -m multiport --dports 6771,6881:6889 -j ACCEPT
            $ipt -A INPUT -p tcp -m multiport --dports 6771,6881:6889 -j ACCEPT

            # open some services for locals
            $ipt -A INPUT -p udp -m multiport --dports 67,68,123,53 -j ACCEPT
            $ipt -A INPUT -p tcp -m multiport --dports 445,139,80,443 -j ACCEPT

            # drop others
            $ipt -A INPUT -j $NFLOG --nflog-prefix "in"
            $ipt -A INPUT -j REJECT

            # redirects
            $ipt -t nat -A OUTPUT -d 127.192.0.0/10 -p tcp -j DNAT --to-destination 127.0.0.1:9052    # tor
            $ipt -t nat -A OUTPUT -m set --match-set TOR dst -p tcp -m multiport --dports 80,443 -j DNAT --to-destination 127.0.0.1:9052    # tor
            #$ipt -t nat -A PREROUTING -i br0 -p tcp --dport 80 -j REDIRECT --to-ports 3128

            # fix dhcpd "bad udp checksums" errors with lxc
            $ipt -A PREROUTING -i br0 -t mangle -p udp --dport 67 -j CHECKSUM --checksum-fill
            $ipt -A POSTROUTING -o br0 -t mangle -p udp --sport 67 -j CHECKSUM --checksum-fill

            # masquerade
            $ipt -t nat -A POSTROUTING -o eth0 -s 10.103.0.0/16  -j MASQUERADE
            $ipt -t nat -A POSTROUTING -o eth0 -s 172.16.0.0/12  -j MASQUERADE
            $ipt -t nat -A POSTROUTING -o eth0 -s 192.168.0.0/16  -j MASQUERADE
            $ipt -t nat -A POSTROUTING -o wlan1 -j MASQUERADE

            # fix for wrong ports by torrent
            $ipt -t nat -A PREROUTING -i wlan1 -p tcp --dport 6881:6889 -j DNAT --to-destination 10.103.10.3:6881
            $ipt -t nat -A PREROUTING -i wlan1 -p udp --dport 6881:6889 -j DNAT --to-destination 10.103.10.3:6881

            ;;

        stop)
            echo "Stopping $msg"
            $ipt -F
            $ipt -t mangle -F
            $ipt -t nat -F
            $ipt -t raw -F
            $ipt -P INPUT ACCEPT
            $ipt -P FORWARD ACCEPT
            $ipt -X TCPSYN
            $ipt -X LDROP
            ipset destroy TOR

            $ip6 -F
            $ip6 -P INPUT ACCEPT
            $ip6 -P FORWARD ACCEPT
            $ip6 -t raw -F
            ;;

        restart)
            $0 stop
            $0 start
            ;;

        status)
            if [ -n "$2" ]; then
                $ipt -n -t $2 -v -L
            else
                $ipt -n -v -L
            fi
            ;;

        flush)
            $ipt -Z
            $ip6 -Z
            $ipt -t nat -Z
            $ipt -t mangle -Z
            $ipt -t raw -Z
            ;;

        *)
            echo "Usage: $0 {start|stop|flush|restart|status}"
            exit 1
            ;;

esac

# End /etc/init.d/
