#!/bin/bash

NAME=$1; shift;

ALREADY=`ip netns | grep -c $NAME`
if [ "$ALREADY" != "1" ]; then
    echo "net space $NAME not exists"
    exit 255
fi

ip netns exec $NAME bash -c "$(printf " %q" "$@")"
