- package: test
  version: 1.0
  architecture: all
  maintainer: Dummy <dummy@example.org>
  homepage: https://github.com/urykhy/stuff
  depends: python, iptables, iproute2
  recommends: ipset
  short: example package
  long: >
    very
    very
    long
    description
  root: /opt/test
  user: root
  group: root
  files:
    - etc:
      - openssl.cnf
    - etc/init.d:
      - zram
    - usr/bin:
      - docker-ddns.py
      - firewall
      - luks.py
      - make_certs
      - sfq
