#!/bin/sh

# shaper works if congestion, ie lower bw if required

prog=""
msg="SFQ"
dev="eth0"
bw="5800kbit"
rate="rate $bw ceil $bw cburst 200kb"
#red="harddrop headdrop redflowlimit 128000 max 64000 ecn"
sfq="sfq perturb 60 divisor 16384 limit 200 depth 64 flows 1024 $red"
#sfq="fq limit 200"
est="estimator 0.5sec 5sec"

qdisc="tc qdisc add dev ifb0"
filter="tc filter add dev ifb0 protocol ip"
class="tc class add dev ifb0"

#bulk_src="mirror.yandex.ru security.debian.org ftp.ru.debian.org"
bulk_src="213.180.204.183 212.211.132.32 212.211.132.250 195.20.242.89 85.143.112.112"

case "$1" in
    start)
		echo "Starting $msg"

		# enable default htb rate estimators
		# not used, since `$est`
		# echo 0 >/sys/module/sch_htb/parameters/htb_rate_est

		modprobe ifb
		ip l set ifb0 up
		tc qdisc add dev $dev ingress
		#tc filter add dev $dev parent ffff: protocol ip u32 match u32 0 0 action mirred egress redirect dev ifb0
		tc filter add dev $dev parent ffff: protocol ip u32 match u32 0 0 action connmark action mirred egress redirect dev ifb0
		$qdisc root handle 1: htb default 102
		$class parent 1: classid 1:10 $est htb $rate quantum 11000      # internet
		$class parent 1: classid 1:20 $est htb rate 1gbit quantum 11000 # for lan
		$class parent 1:10 classid 1:100 $est htb rate 1mbit ceil $bw prio 1 # prio
		$class parent 1:10 classid 1:101 $est htb rate 4mbit ceil $bw prio 2 # www
		$class parent 1:10 classid 1:102 $est htb rate 1mbit ceil $bw prio 3 # bulk
		$qdisc parent 1:100 handle 100: $sfq
		$qdisc parent 1:101 handle 101: $sfq
		$qdisc parent 1:102 handle 102: $sfq

		# lan
		$filter parent 1: prio 1 u32 match ip src 192.168.0.0/16 flowid 1:20

        # bulk is default + add debian mirrors
        for ip in $bulk_src; do
            $filter parent 1: prio 2 u32 match ip src $ip/32 flowid 1:102 #
        done

        # bulk prio by iptables
        # long downloads
		$filter parent 1: prio 3 handle 0xa fw flowid 1:102
        # skype. UDP from wlan
		$filter parent 1: prio 4 handle 0xb fw flowid 1:101

		# prio traffic
		$filter parent 1: prio 10 u32 match ip sport 22 0xffff flowid 1:100    # ssh
		$filter parent 1: prio 10 u32 match ip sport 53 0xffff flowid 1:100    # dns
		$filter parent 1: prio 10 u32 match ip sport 123 0xffff flowid 1:100   # ntp
		$filter parent 1: prio 10 u32 match ip sport 5190 0xffff flowid 1:100  # icq
		$filter parent 1: prio 10 u32 match ip sport 5222 0xffff flowid 1:100  # xmpp
		$filter parent 1: prio 10 u32 match ip sport 5223 0xffff flowid 1:100  # xmpp
		$filter parent 1: prio 10 u32 match ip sport 6667 0xffff flowid 1:100  # irc
		$filter parent 1: prio 10 u32 match ip sport 9944 0xffff flowid 1:100  # irc
		$filter parent 1: prio 10 u32 match ip sport 28763 0xffff flowid 1:100 # assalutcube
		$filter parent 1: prio 10 u32 match ip sport 28764 0xffff flowid 1:100
		$filter parent 1: prio 10 u32 match ip dport 1027 0xffff flowid 1:100  # skype/settings/advanced/
		$filter parent 1: prio 10 u32 match ip protocol 1 0xff flowid 1:100    # icmp
		$filter parent 1: prio 10 u32 match ip sport 1022 0xffff flowid 1:100  # ssh/pg

		# www, pop3, imap4, imaps
		$filter parent 1: prio 20 u32 match ip sport 80 0xffff flowid 1:101    # http
		$filter parent 1: prio 20 u32 match ip sport 443 0xffff flowid 1:101   # https
		$filter parent 1: prio 20 u32 match ip sport 143 0xffff flowid 1:101   # imap
		$filter parent 1: prio 20 u32 match ip sport 110 0xffff flowid 1:101   # pop3
		$filter parent 1: prio 20 u32 match ip sport 993 0xffff flowid 1:101   # imaps
		$filter parent 1: prio 20 u32 match ip sport 1122 0xffff flowid 1:101  # open vpn

		tc qdisc add dev $dev root $sfq
	;;
	stop)
		echo "Stopping $msg"
		tc qdisc del dev $dev root
		tc qdisc del dev ifb0 root
		tc qdisc del dev $dev handle ffff: ingress
		ip l set ifb0 down
		rmmod ifb
	;;

	restart)
		$0 stop
		$0 start
	;;

	status)
		if [ -z "$2" ]; then
			tc -s qdisc show dev ifb0 | grep 'back\|dropped\|^qdisc'
		fi
		if [ "$2" = "class" ]; then
			tc -s class show dev ifb0
		fi
		if [ "$2" = "filter" ]; then
			tc -s filter show dev $dev parent ffff:
			tc -p -s filter show dev ifb0 parent 1:
		fi
	;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;

esac

# End /etc/init.d/
